language: android
dist: trusty
jdk: oraclejdk8
sudo: false

deploy:
  provider: firebase

android:
  components:
  - build-tools-29.0.0
  - android-15
  - add-on
  - extra-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-x86-android-25
  - sys-img-armeabi-v7a-google_apis-google-25
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
- yes | sdkmanager "platforms;android-25"
- yes | sdkmanager "platforms;android-26"
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager "platforms;android-28"

install: true

before_script:
# Download and install gcloud cli to run firebase test commands
- wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-218.0.0-linux-x86.tar.gz
- tar zxf google-cloud-sdk-218.0.0-linux-x86.tar.gz google-cloud-sdk
- echo n | ./google-cloud-sdk/install.sh
- ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file https://firebasestorage.googleapis.com/v0/b/my-news-8af6b.appspot.com/o/my-news-8af6b-c2c2b4cbe7c7.json?alt=media&token=2b78f359-6d86-467b-828f-c68adb759aff
- ./google-cloud-sdk/bin/gcloud config set project my-news-8af6b
- echo y | ./google-cloud-sdk/bin/gcloud components update
- echo y | ./google-cloud-sdk/bin/gcloud components install beta



script:
- chmod +x gradlew
- ./gradlew assembleDebug
- ./gradlew assembleDebugAndroidTest
- ./google-cloud-sdk/bin/gcloud beta firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk –test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk –device model=Pixel2,version=29
- ./gradlew connectedCheck --stacktrace

env:
  global:
    secure: ZIqxlXG7LJtAXYFARrk3LVE8tva32vd4T1jJCdSqcoz1lKSDEXufE50tXwPtCpDE/f1ZTkIkVqTskxvZ84B0TpAQyjUzGc7O1/A+Ez2IImKfTxPw3GKHfwOcUQw1tpduw7o/2SoS3eAR6cGIumCye5417nryvsiSp3U2FAXx842ooxjJU1tMtnNfNkKTV4eds/kC0CEPy9TeuVYe5yaQn6KtZX3Tle0NQrMoyMU1g34xoAd3jmIa0vEuyZMK7UI2gRiadrvsOpKjru7Cn/wc1Xyb4ylPgRtNxkhLsneRt1Gem4Hzoujq2tKuvJrupm9tSTYiWWwxcy1ER+SzvEJdhtBPvNq7hh8VpEgRknh1ZzksuooX8EgiGABlmdsW+H5Nuio2q4NfLF0x3yzVxGOZU2OrVDONEHP7oA3Nu1Ju+q5zLDceHIoicAmicBJJcpoNGQ9JQtTojlHcCOM3iWyL+E7o059QzX8o53opdc4EW6H+4PHJetH+hS8Q9AeqnxNYsxiWP67LOsgmP3jTPS7xV0p0FYIK+dnJxVYNwbJMRjWViFO30fFcbOurgvRfJeI7nN/EdH5IHMkZ3K0sUaCdhuSq+vkoY/HEnY+LhPGcCwmKfZlmSHyMXIgsgCsVDruPrhB3Rd4u8ed5sKXmWxrzbSfBS+PdjDnrIUwL9q85f4Q=
